name: Good CI/CD Workflow

on: 
  push:
    branches:
      - master

jobs:
  good-practices:
    runs-on: ubuntu-latest
    steps:
      - name: Use Secrets
        env:
          SECRET_PASSWORD: ${{ secrets.SECRET_PASSWORD }}
        run: echo "Using secrets securely"

      - name: Remove root usage
        run: echo "Performing tasks with minimal privileges"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: pytest tests/

      - name: Deploy code
        run: |
          echo "Deploying to production..."
          curl -X POST http://example.com/deploy --data '{"branch": "master"}'
